/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const EffectScope: typeof import('@vue/composition-api')['EffectScope']
  const computed: typeof import('@vue/composition-api')['computed']
  const createApp: typeof import('@vue/composition-api')['createApp']
  const customRef: typeof import('@vue/composition-api')['customRef']
  const defineAsyncComponent: typeof import('@vue/composition-api')['defineAsyncComponent']
  const defineComponent: typeof import('@vue/composition-api')['defineComponent']
  const effectScope: typeof import('@vue/composition-api')['effectScope']
  const getCurrentInstance: typeof import('@vue/composition-api')['getCurrentInstance']
  const getCurrentScope: typeof import('@vue/composition-api')['getCurrentScope']
  const h: typeof import('@vue/composition-api')['h']
  const inject: typeof import('@vue/composition-api')['inject']
  const isProxy: typeof import('@vue/composition-api')['isProxy']
  const isReactive: typeof import('@vue/composition-api')['isReactive']
  const isReadonly: typeof import('@vue/composition-api')['isReadonly']
  const isRef: typeof import('@vue/composition-api')['isRef']
  const markRaw: typeof import('@vue/composition-api')['markRaw']
  const nextTick: typeof import('@vue/composition-api')['nextTick']
  const onActivated: typeof import('@vue/composition-api')['onActivated']
  const onBeforeMount: typeof import('@vue/composition-api')['onBeforeMount']
  const onBeforeUnmount: typeof import('@vue/composition-api')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('@vue/composition-api')['onBeforeUpdate']
  const onDeactivated: typeof import('@vue/composition-api')['onDeactivated']
  const onErrorCaptured: typeof import('@vue/composition-api')['onErrorCaptured']
  const onMounted: typeof import('@vue/composition-api')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('@vue/composition-api')['onScopeDispose']
  const onServerPrefetch: typeof import('@vue/composition-api')['onServerPrefetch']
  const onUnmounted: typeof import('@vue/composition-api')['onUnmounted']
  const onUpdated: typeof import('@vue/composition-api')['onUpdated']
  const provide: typeof import('@vue/composition-api')['provide']
  const reactive: typeof import('@vue/composition-api')['reactive']
  const readonly: typeof import('@vue/composition-api')['readonly']
  const ref: typeof import('@vue/composition-api')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('@vue/composition-api')['shallowReactive']
  const shallowReadonly: typeof import('@vue/composition-api')['shallowReadonly']
  const shallowRef: typeof import('@vue/composition-api')['shallowRef']
  const toRaw: typeof import('@vue/composition-api')['toRaw']
  const toRef: typeof import('@vue/composition-api')['toRef']
  const toRefs: typeof import('@vue/composition-api')['toRefs']
  const toValue: typeof import('@vue/composition-api')['toValue']
  const triggerRef: typeof import('@vue/composition-api')['triggerRef']
  const unref: typeof import('@vue/composition-api')['unref']
  const useAttrs: typeof import('@vue/composition-api')['useAttrs']
  const useCssModule: typeof import('@vue/composition-api')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useSlots: typeof import('@vue/composition-api')['useSlots']
  const watch: typeof import('@vue/composition-api')['watch']
  const watchEffect: typeof import('@vue/composition-api')['watchEffect']
  const watchPostEffect: typeof import('@vue/composition-api')['watchPostEffect']
  const watchSyncEffect: typeof import('@vue/composition-api')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, VNode, WritableComputedRef } from '@vue/composition-api'
}
