export { default as FaFormDialog } from './components/FormDialog/index.vue';
export { default as FaImage } from './components/Image/index.vue';
export { default as FaImageUpload } from './components/ImageUpload/index.vue';
export { default as FaMessageBox } from './components/MessageBox/index';
export { default as FaPopButton } from './components/PopButton/index.vue';
export { default as FaPopSwitch } from './components/PopSwitch/index.vue';
export { default as FaRichText } from './components/RichText/index';
export { default as FaSelect } from './components/Select/index.vue';
export { default as FaUpload } from './components/Upload/index.vue';
